trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  projects: '**/*.csproj'
  testProjects: '**/*Tests/*.csproj'
  clientApp: 'outagemap.client'
  serverProject: 'OutageMap.Server/OutageMap.Server.csproj'

steps:

- task: UseDotNet@2
  displayName: 'Install .NET SDK'
  inputs:
    packageType: 'sdk'
    version: '10.0.x'

- task: NodeTool@0
  displayName: 'Install Node.js'
  inputs:
    versionSpec: '22.x'

- task: DotNetCoreCLI@2
  displayName: 'Restore'
  inputs:
    command: 'restore'
    projects: '$(projects)'

- script: npm ci
  workingDirectory: '$(clientApp)'
  displayName: 'npm install'

- script: npm run lint
  workingDirectory: '$(clientApp)'
  displayName: 'npm lint'

- task: DotNetCoreCLI@2
  displayName: 'Build'
  inputs:
    command: 'build'
    projects: '$(projects)'
    arguments: '--configuration $(buildConfiguration) --no-restore'

- task: DotNetCoreCLI@2
  displayName: 'Test'
  inputs:
    command: 'test'
    projects: '$(testProjects)'
    arguments: '--configuration $(buildConfiguration) --no-build'

- task: DotNetCoreCLI@2
  displayName: 'Publish'
  inputs:
    command: 'publish'
    publishWebProjects: false
    projects: '$(serverProject)'
    arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)/app'
    zipAfterPublish: true
  env:
    VITE_MAPBOX_TOKEN: $(VITE_MAPBOX_TOKEN)
    VITE_DEMO_MODE: 'true'

- task: AzureWebApp@1
  displayName: 'Deploy to Azure App Service'
  inputs:
    azureSubscription: 'azure-outagemap'
    appType: 'webAppLinux'
    appName: 'outagemap-houston'
    package: '$(Build.ArtifactStagingDirectory)/app/*.zip'